/** Localized setup and loading surfaces available before the official client starts. */
const en = { tagline: 'Explore the Uncharted', preview: 'Preview', checking: 'Checking the environment…', loading: 'Loading Harness…', node: 'Node.js is unavailable or unsupported. Install Node.js 22.19+ (22.x) or 24+, add it to PATH, then restart VS Code. For SSH, install it on the remote host.', download: 'Download Node.js', bin: 'Official DSH bin.js was not found. Provide its absolute file path or an installed DSH directory.', binAction: 'Enter bin.js path', directoryAction: 'Enter DSH directory', binPrompt: 'Absolute path to the official DSH bin.js file', directoryPrompt: 'Absolute directory of the installed and built DSH runtime', retry: 'Check again', invalid: 'Enter a valid absolute path to an installed DSH runtime.', saved: 'DSH path saved in VS Code user settings on this host.' };
const zh: typeof en = { tagline: '探索未至之境', preview: '预览版', checking: '正在检查运行环境…', loading: '正在加载 Harness…', node: 'Node.js 未找到或版本不满足要求。请安装 Node.js 22.19+（22.x）或 24+，加入 PATH 后重启 VS Code。SSH 工作区请在远程机器安装。', download: '前往 Node.js 官方下载', bin: '未找到官方 DSH 的 bin.js，请填写文件绝对路径或已安装的 DSH 目录。', binAction: '填写 bin.js 路径', directoryAction: '填写 DSH 目录', binPrompt: '官方 DSH bin.js 文件的绝对路径', directoryPrompt: '已安装依赖并构建完成的 DSH 目录绝对路径', retry: '重新检测', invalid: '请填写有效的已安装 DSH 绝对路径。', saved: 'DSH 路径已保存到当前运行主机的 VS Code 用户设置。' };

/** @param language - VS Code language. @returns Setup copy for that locale. */
export function startupCopy(language: string): typeof en { return language.toLowerCase().startsWith('zh') ? zh : en; }

/** Failures are independent so both missing prerequisites can be repaired. */
export interface StartupState { nodeError?: string; binError?: string; message?: string; retry?: boolean }

/** @param language - VS Code language. @param nonce - Script nonce. @param whale - Trusted bundled SVG. @param state - Loading or setup status. @returns A self-contained, network-free initial page. */
export function startupHtml(language: string, nonce: string, whale: string, state: StartupState): string {
  const t = startupCopy(language);
  const escape = (s: string): string => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
  const setup = state.nodeError !== undefined || state.binError !== undefined;
  const button = (action: string, label: string): string => `<button${action === 'retry' ? ' id="retry"' : ''} data-action="${action}">${escape(label)}</button>`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'"><style>
html,body{margin:0;min-height:100%;background:var(--vscode-editor-background);color:var(--vscode-foreground)}body{font:13px var(--vscode-font-family);display:grid;place-items:center;min-height:100vh}.page{width:min(440px,calc(100% - 40px));text-align:center;padding:32px 0}.whale svg{width:58px;height:44px;color:#4d6bfe}h1{font-size:22px;font-weight:500;margin:20px 0 10px}.badge{font-size:11px;opacity:.65}.spinner{width:22px;height:22px;border:2px solid var(--vscode-widget-border,#8884);border-top-color:#4d6bfe;border-radius:50%;animation:spin 1s linear infinite;margin:24px auto 12px}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.spinner{animation-duration:3s}}section{text-align:left;padding:16px;margin-top:20px;border:1px solid var(--vscode-widget-border,#8884);border-radius:10px}p{line-height:1.7;overflow-wrap:anywhere}button{font:inherit;padding:8px 12px;margin:4px;border:0;border-radius:5px;cursor:pointer;color:var(--vscode-button-foreground);background:var(--vscode-button-background)}button:focus-visible,a:focus-visible{outline:2px solid var(--vscode-focusBorder)}a{color:var(--vscode-textLink-foreground)}.detail{opacity:.65;font-size:12px}
</style></head><body><main class="page"><div class="whale" aria-hidden="true">${whale}</div><h1>${escape(t.tagline)}</h1><span class="badge">${escape(t.preview)}</span>
${setup ? '' : `<div class="spinner" aria-hidden="true"></div><p role="status">${escape(state.message ?? t.loading)}</p>`}
${state.nodeError !== undefined ? `<section><strong>Node.js</strong><p>${escape(t.node)}</p><p class="detail">${escape(state.nodeError)}</p><a href="https://nodejs.org/en/download" id="node-download">${escape(t.download)}</a></section>` : ''}
${state.binError !== undefined ? `<section><strong>DSH bin.js</strong><p>${escape(t.bin)}</p><p class="detail">${escape(state.binError)}</p>${button('setup-bin', t.binAction)}${button('setup-directory', t.directoryAction)}</section>` : ''}
${setup || state.retry ? button('retry', t.retry) : ''}</main><script nonce="${nonce}">const api=acquireVsCodeApi();for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>api.postMessage({kind:b.dataset.action});const link=document.getElementById('node-download');if(link)link.onclick=e=>{e.preventDefault();api.postMessage({kind:'setup-node-download'})};</script></body></html>`;
}
